export type AppView =
    | 'home'
    | 'dashboard'
    | 'carteira'
    | 'carteira_grupo'
    | 'acoes_promocionais'
    | 'pedido_mensal'
    | 'crm'
    | 'cd_desempenho'
    | 'churn'
    | 'cs_kpis'
    | 'todos_parceiros'
    | 'settings'
    | 'about'
    | 'managers'
    | 'profile'
    | 'contacts'
    | 'reports';
